# Generated by Django 4.2 on 2023-04-12 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
